- construi.yml
- construi/deploy/script.sh
- construi/release/script.sh
- lib/construi/container.rb
Refactor construi.yml in light of that change
Fixes #6
> Remove running of commands in /bin/sh

- construi.gemspec
- lib/construi.rb
- lib/construi/config.rb
- lib/construi/image.rb
> Allow building image from Dockerfile

- lib/construi.rb
- lib/construi/config.rb
- lib/construi/image.rb
> Allow image/build to be given per target

- lib/construi/container.rb
- spec/lib/container_spec.rb
> Fix error message with status code on failure

- README.md
- construi.gemspec
> Improve dependencies.

- construi.yml
- construi/deploy/script.sh
- construi/release/script.sh
Also attempt to fix always failing deploy script
Fixes #29 
Fixes #33
> Update release/deployment to use files feature

- construi.yml
- spec/spec_helper.rb
> Only run coverage if explictly enabled

- construi.gemspec
- lib/construi/runner.rb
- lib/construi/version.rb
> Upgrade dependency versions

- lib/construi/runner.rb
Also minor rubucop fixes
Fixes #56
> Remove read timeout for Docker api

- lib/construi/image.rb
- spec/lib/construi/image_spec.rb
If a docker entrypoint required a privileged flag it would crash the
build when performing the chmod or ls step of copying files
> Pass through privileged when copying files

- lib/construi/config.rb
- site/index.md
- spec/lib/construi/config_spec.rb
- spec/lib/construi/image_spec.rb
> Target specific environment Variables

- bin/construi
- lib/construi.rb
- lib/construi/config.rb
- lib/construi/console.rb
- lib/construi/container.rb
- lib/construi/image.rb
- lib/construi/runner.rb
- lib/construi/target.rb
- site/index.md
- spec/lib/construi/config_spec.rb
- spec/lib/construi/container_spec.rb
- spec/lib/construi/image_spec.rb
- spec/lib/construi/runner_spec.rb
> Linking of containers

- lib/construi/config.rb
- lib/construi/console.rb
- lib/construi/container.rb
- lib/construi/options.rb
- lib/construi/runner.rb
- lib/construi/target.rb
- spec/lib/construi/container_spec.rb
- spec/lib/construi/runner_spec.rb
> Allow use of volumes and volumes_from

- .gitignore
- construi.yml
- construi/__init__.py
- docker/release/Dockerfile
- scripts/version.sh
- setup.py
> Release Scripts

- LICENSE
- README.md
- setup.py
Also add LICENSE and very basic README
> More details in setup.py

- construi.yml
- construi/cli.py
- construi/config.py
- construi/console.py
- construi/target.py
- setup.py
> Add flake8 checking

- construi.yml
- construi/cli.py
- construi/config.py
- construi/target.py
- test/test_config.py
Allow specifying tasks that must be run before the current task.
Also add `--dry-run` option to view running order of tasks.
> Before tasks

- construi.yml
- scripts/release.sh
- scripts/twine.sh
Tag release. Include DRY_RUN setting for testing
> Refine release script

- construi/target.py
Docker building likes containers names to not have uppercase
> Use only lowercase letters

- construi/config.py
- construi/target.py
- test/test_config.py
This is useful for allowing targets that are just collections of other
targets
> Allow run to be empty in targets.

- construi/config.py
- construi/target.py
- setup.py
> Update to docker-compose 1.6.0

- construi.yml
- construi/config.py
- test/test_config.py
- test/test_sanity.py
> Remove build/image from base if given in target

- construi/config.py
- construi/target.py
After doing this, we will reduce images we created, and keep the build
cache
> Change image name to construi_<project>_<target>

- README.md
> Add Travis CI usage docs

- README.md
- construi.yml
- construi/config.py
- construi/target.py
>  Allow setting of shell for target

- README.md
- construi/cli.py
> Allow extra args to be passed to targets

- construi/cli.py
- test/test_cli.py
> Fix py3 incompatable exception catching syntax

- construi/target.py
- setup.py
> Use auto docker api version

- construi.yml
- construi/config.py
- setup.py
> Update docker compose version

- .gitignore
- Dockerfile.mypy
- construi.yml
- construi/cli.py
- construi/config.py
- construi/console.py
- construi/target.py
- setup.py
The docker compose package upgrade was causing errors on building images related to osxkeychain credentials.
> Add mypy, rollback docker-compose upgrade

- .travis.yml
- requirements.in
- requirements.txt
- setup.py
To work with latest travis images
> Lib upgrades
